module.exports = function filter_html(fileToRead) {
  let file_text = ``;

  const filterted_files = fileToRead?.Sources?.filter((source) => {
    for (sharedgpt of source.ChatgptSharing) {
      if (sharedgpt?.Conversations)
        for (conversation of sharedgpt.Conversations) {
          for (codeItem of conversation.ListOfCode) {
            if (codeItem?.Type === "html") return true;
          }
        }
    }
  });

  // console.log(" Number of entries with HTML code: " + filterted_files.length);
  file_text = ` Number of entries with HTML code: ${filterted_files.length}`;
  const helperObj = {};

  for (item of filterted_files) {
    if (Object.keys(helperObj).includes(item.RepoLanguage)) {
      helperObj[item.RepoLanguage] += 1;
    } else {
      helperObj[item.RepoLanguage] = 1;
    }
  }
  // console.log(
  //   " Repository Languages of the entries with HTML code generated by chatGPT:",
  // );
  file_text +=
    "\n Repository Languages of the entries with HTML code generated by chatGPT:\n";
  for (var prop in helperObj) {
    // console.log("   Language " + prop + " = " + helperObj[prop]);
    file_text += `   ${prop} = ${helperObj[prop]}\n`;
  }

  return file_text;
};
